baseURL = "http://www.kingrando.com/"
languageCode = "en-us"
title = "Kameron Ingrando"
copyright = "2020 Kameron Ingrando"

[params]
  github = "your_github"
  linkedin = "your_linkedin"
  twitter = "your_twitter"

[markup]
  [markup.highlight]
    style = "monokailight"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Zettels"
url = "/zettels"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
name = "Resources"
url = "/resources"
weight = 2