baseURL = "https://www.kingrando.com/"
languageCode = "en-us"
title = "Kameron Ingrando"
copyright = "Kameron Ingrando"

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "Notes"
url = "/notes"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Useful Links"
url = "/useful-links"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 6

[params]
  postSection = "posts"
  notesSection = "notes"
  showAllPostsOnHomePage = false
  postsOnHomePage = 10
  tagsOverview = false
  showNotesList = true

[[params.social]]
  name = "GithubID"
  link = "kingrando"

[[params.social]]
  name = "Email"
  link = "kameron.ingrando@gmail.com"

[[params.social]]
  name = "LinkedInID"
  link = "kameroningrando"

[[params.social]]
  name = "TwitterID"
  link = "kameroningrando"
  
