baseURL = "https://www.kingrando.com/"
languageCode = "en-us"
title = "Kameron Ingrando"
copyright = "2020 Kameron Ingrando"

[taxonomies]
tag = "tags"

[params]
  GithubID = "kingrando"
  LinkedInID = "kingrando"
  TwitterID = "KameronIngrando"
  Email = "kameron.ingrando@gmail.com"

[markup]
  [markup.highlight]
    style = "monokailight"

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "Zettels"
url = "/zettels"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 1

[[menu.main]]
name = "Resources"
url = "/resources"
weight = 1

[related]
threshold = 80.0
includeNewer = true
toLower = false

  [[related.indices]]
  name = "id"
  weight = 100.0

  [[related.indices]]
  name = "tags"
  weight = 10.0