baseURL = "https://kingrando.com/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disablePathToLower = false
enableEmoji = false
enableGitInfo = false
enableRobotsTXT = true
footnoteReturnLinkContents = "↩"
hasCJKLanguage = false
languageCode = "en"
newContentEditor = ""
paginate = 5
pluralizeListTitles = false
relativeURLs = false
summaryLength = 42
theme = "meme"
title = "Kameron Ingrando"
uglyURLs = false
[author]
name = "Kameron Ingrando"
[frontmatter]
lastmod = ["lastmod", ":git", ":fileModTime", ":default"]
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.parser]
attribute = true
autoHeadingID = true
autoHeadingIDType = "github"
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false
[markup.highlight]
codeFences = true
guessSyntax = false
lineNos = true
lineNumbersInTable = true
noClasses = false
[markup.tableOfContents]
endLevel = 6
ordered = true
startLevel = 2
[mediaTypes."application/atom+xml"]
suffixes = ["xml"]
[[menu.main]]
name = "About"
post = "user-circle"
pre = "internal"
url = "/about/"
weight = 6
[[menu.main]]
name = "Useful Resources"
post = "link"
pre = "internal"
url = "/useful-resources/"
weight = 5
[[menu.main]]
name = "Categories"
post = "th"
pre = "internal"
url = "/categories/"
weight = 3
[[menu.main]]
name = "Notes"
post = "folder"
pre = "internal"
url = "/notes/"
weight = 2
[[menu.main]]
name = "Posts"
post = "archive"
pre = "internal"
url = "/posts/"
weight = 1
[[menu.main]]
name = "Tags"
post = "tags"
pre = "internal"
url = "/tags/"
weight = 4
[outputFormats.SearchIndex]
baseName = "search"
mediaType = "application/json"
[outputFormats.SectionsAtom]
baseName = "atom"
mediaType = "application/atom+xml"
[outputFormats.SectionsRSS]
baseName = "rss"
mediaType = "application/rss+xml"
[outputs]
home = ["HTML", "SectionsAtom", "SectionsRSS", "SearchIndex"]
page = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]
[params]
activeInSection = false
anchorIcon = "link"
anchorSymbol = "#"
autoDetectImages = true
autoHideLangToggle = true
backToTopIcon = "arrow-up"
badgeTitlePrefix = "Updated @ "
busuanziPagePVIcon = "eye"
busuanziSitePVIcon = "eye"
busuanziSitePVText = "Site PV"
busuanziSiteUVIcon = "user"
busuanziSiteUVText = "Site UV"
captionPrefix = "◎ "
categoryBy = "categories"
categoryDelimiter = "/"
categoryIcon = "folder"
chineseZodiac = true
customFooter = ""
defaultTheme = "light"
deleteHrBeforeDropCap = false
disableMathJaxMenu = false
displayBackToTopInHome = true
displayBusuanziPagePV = false
displayBusuanziSiteUVAndPV = false
displayCategory = true
displayCommitHash = true
displayCommitMessage = true
displayCopyrightSymbol = true
displayEditLink = true
displayExpiredDate = true
displayFeedback = true
displayFooter = true
displayFooterInHome = true
displayHeaderInHome = true
displayListTitle = true
displayMenuInHome = true
displayModifiedDate = true
displayPostCopyright = true
displayPostDescription = true
displayPostGitInfo = false
displayPostShare = true
displayPosts = true
displayPostsCount = true
displayPoweredBy = true
displayPublishedDate = true
displayReadingTime = true
displayRelatedPosts = true
displayShareOnText = false
displaySiteCopyright = true
displaySiteCreatedYear = true
displayTOCNum = true
displayTOCTitle = true
displayTaxonomyTermCount = true
displayUpdatedBadge = false
displayWordCount = true
disqusShortname = ""
duration = 0.5
editIcon = "edit"
editText = "Edit Me?"
enableAboutPageMinimalFooter = false
enableAnchorAutoHide = true
enableAnchorLink = true
enableBackToTop = true
enableBackToTopAutoHide = true
enableBadgeTitle = true
enableCaption = true
enableChinesePunctuationGlyphCorrection = false
enableComments = false
enableCopy = true
enableCopyAutoHide = true
enableDarkMode = true
enableDisqus = false
enableDropCap = false
enableDropCapAfterHr = false
enableEmphasisPoint = false
enableFingerprint = true
enableFooter = true
enableForceHTTPS = false
enableGoogleAdUnits = false
enableGoogleAnalytics = false
enableGoogleAutoAds = false
enableHeader = true
enableHeadingsAnchor = true
enableHighlight = true
enableImageHost = false
enableInstantPage = true
enableJustify = false
enableKaTeX = false
enableLangToggle = false
enableLunrSearch = true
enableMathJax = false
enableMediumZoom = true
enableMenu = true
enableMermaid = false
enableMinimalFooter = false
enableNavToggle = true
enableOverflowY = true
enableParagraphIndent = true
enablePostCopyright = true
enablePostGitInfo = false
enablePostMeta = true
enablePostMetaInHome = true
enablePostNav = true
enablePostShare = false
enablePostTags = true
enablePostUpdatedBadge = true
enableRelatedPosts = true
enableServiceWorker = false
enableSmallCaps = true
enableSmoothScroll = true
enableSocials = true
enableTOC = false
enableTagCloud = true
enableTree = true
enableUtterances = false
enableValine = false
enableVerticalBarStructure = false
enableVideoHost = false
expiredDateIcon = "calendar-times"
feedbackIcon = "question"
feedbackText = "Feedback"
fofPoster = ""
fofVideoMp4 = ""
fofVideoWebm = ""
fontFamilyBody = "'IBM Plex Serif', serif"
fontFamilyCaption = ""
fontFamilyCode = "'Source Code Pro', monospace"
fontFamilyFooter = ""
fontFamilyHeadings = "'Comfortaa', sans-serif"
fontFamilyMenu = ""
fontFamilyQuote = ""
fontFamilySiteBrand = ""
fontFamilyTOC = ""
fontFamilyTitle = "'Comfortaa', sans-serif"
fontSize = 18
fontUnit = "em"
fontsLink = "https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:ital,wght@0,400;0,500;0,700;1,400;1,700&family=Source+Code+Pro:ital,wght@0,400;0,700;1,400;1,700&family=Comfortaa:wght@700&display=swap"
footnoteReturnLinkIcon = "angle-up"
gitIcon = "code-branch"
googleAdClient = ""
googleAdSlot = ""
googleSiteVerification = ""
groupByMonth = true
headAlso = false
headerBackground = "linear-gradient();"
headerLayout = "flex"
headingsOpt = "1-6"
hideLangToggleInHome = false
hideThemeToggle = false
hideThemeToggleInHome = false
homeDescription = ""
homeKeywords = ""
homeLayout = "posts"
homeLinksDelimiter = ""
homeLinksPadding = 1
homeLogo = ""
homeLogoLink = ""
homeMotto = ""
homePoetry = []
homePoster = ""
homeTitle = ""
homeVideoMp4 = ""
homeVideoWebm = ""
hrefTargetBlank = true
i18nMonth = false
i18nYear = false
iconAnimation = true
iconBetweenYearAndAuthor = ""
iconColor = "#f06292"
imageHostURL = "https://example.com/"
includeContent = true
indentFirstParagraph = false
insertHrBySelf = true
jsonLD = true
largestFontSize = 2.5
limitEntriesLimit = -1
limitPostsLimit = -1
lineHeight = 1.618
linkHeadingsToTOC = true
listDateFormat = "January 2"
listDatePosition = "right"
listWidth = ""
mainSections = ["posts"]
maxHeight = 20
mermaidTheme = "default"
mermaidThemeDark = "dark"
modifiedDateIcon = "calendar-check"
msApplicationTileColor = "#fff"
msgIcon = "info"
navHeight = "10em"
openGraph = true
original = false
overrideSystemPreferences = false
paragraphStyle = "margin"
postMetaDateFormat = "2006.1.2"
postNavInSection = true
postTagsIcon = "tag"
postWidth = ""
primaryColorDark = "201, 65%, 62%"
primaryColorLight = "220, 90%, 56%"
publishedDateIcon = "calendar-alt"
readingTimeIcon = "clock"
relatedPostsIcon = "plus-circle"
relatedPostsNumber = 5
repoEditURL = ""
repoURL = ""
safariMaskColor = "#2a6df4"
shareOnDouban = false
shareOnFacebook = false
shareOnLinkedIn = true
shareOnQQ = false
shareOnQzone = false
shareOnTelegram = false
shareOnTwitter = true
shareOnWeibo = false
shareViaQRCode = false
siteBrandFontColor = "var(--color-contrast-high)"
siteBrandFontSize = 1
siteBrandSVG = false
siteBrandSVGFill = "#fff"
siteBrandSVGHeight = 100
siteBrandSVGWidth = 250
siteCreatedTime = "2020-05-20T15:27:27-05:00"
siteDescription = "Personal blog and notes covering automation, networking, and other interests. "
siteLogo = "/icons/apple-touch-icon.png"
smallestFontSize = 1
squareBrackets = true
tabSize = 4
themeColor = "#fff"
themeColorDark = "#16171d"
trackingCodeType = "gtag"
trackingID = ""
twitterCards = true
utterancesIssueTerm = "pathname"
utterancesLabel = ""
utterancesRepo = ""
utterancesTheme = "github-light"
utterancesThemeDark = "photon-dark"
valineAppId = ""
valineAppKey = ""
valineAvatar = "mm"
valineAvatarForce = false
valineEmojiCDN = ""
valineEnableQQ = false
valineHighlight = true
valineLang = "en"
valineMeta = ["nick", "mail", "link"]
valinePageSize = 10
valinePath = ""
valinePlaceholder = "Just go go"
valineRecordIP = false
valineRequiredFields = []
valineServerURLs = ""
valineVisitor = false
videoHostURL = "https://example.com/"
wordCountIcon = "pencil-alt"
[params.valineEmojiMaps]
[permalinks]
categories = "/categories/:slug/"
notes = "/:section/:year/:month/:day/:title/"
posts = "/:section/:year/:month/:day/:title/"
tags = "/tags/:slug/"
useful-resources = "/:section/:title/"
[related]
includeNewer = true
threshold = 80
toLower = true
[[related.indices]]
name = "categories"
weight = 100
[[related.indices]]
name = "tags"
weight = 95
[[related.indices]]
name = "date"
pattern = "2006"
weight = 10
[services.rss]
limit = -1
[taxonomies]
category = "categories"
tag = "tags"
